const apps = [
    { name: "Altus", img: "altus-logo.png", url: "https://github.com/linuxserver/docker-altus" },
    { name: "Ardour", img: "ardour-logo.png", url: "https://github.com/linuxserver/docker-ardour" },
    { name: "Audacity", img: "audacity-logo.png", url: "https://github.com/linuxserver/docker-audacity" },
    { name: "Azahar", img: "azahar-logo.png", url: "https://github.com/linuxserver/docker-azahar" },
    { name: "Bambustudio", img: "bambustudio-logo.png", url: "https://github.com/linuxserver/docker-bambustudio" },
    { name: "Blender", img: "blender-logo.png", url: "https://github.com/linuxserver/docker-blender" },
    { name: "Boinc", img: "boinc-logo.png", url: "https://github.com/linuxserver/docker-boinc" },
    { name: "Brave", img: "brave-logo.png", url: "https://github.com/linuxserver/docker-brave" },
    { name: "Calibre", img: "calibre-logo.png", url: "https://github.com/linuxserver/docker-calibre" },
    { name: "Calligra", img: "calligra-logo.png", url: "https://github.com/linuxserver/docker-calligra" },
    { name: "Chrome", img: "chrome-logo.png", url: "https://github.com/linuxserver/docker-chrome" },
    { name: "Chromium", img: "chromium-logo.png", url: "https://github.com/linuxserver/docker-chromium" },
    { name: "Citron", img: "citron-logo.png", url: "https://github.com/linuxserver/docker-citron" },
    { name: "Cura", img: "cura-logo.png", url: "https://github.com/linuxserver/docker-cura" },
    { name: "Darktable", img: "darktable-logo.png", url: "https://github.com/linuxserver/docker-darktable" },
    { name: "Digikam", img: "digikam.png", url: "https://github.com/linuxserver/docker-digikam" },
    { name: "Dogwalk", img: "dogwalk-logo.png", url: "https://github.com/linuxserver/docker-dogwalk" },
    { name: "Dolphin", img: "dolphin-logo.png", url: "https://github.com/linuxserver/docker-dolphin" },
    { name: "Dosbox Staging", img: "dosbox-logo.png", url: "https://github.com/linuxserver/docker-dosbox-stating" },
    { name: "Doublecommander", img: "doublecommander-icon.png", url: "https://github.com/linuxserver/docker-doublecommander" },
    { name: "Duckstation", img: "duckstation-logo.png", url: "https://github.com/linuxserver/docker-duckstation" },
    { name: "Ferdium", img: "ferdium-logo.png", url: "https://github.com/linuxserver/docker-ferdium" },
    { name: "Filezilla", img: "filezilla-logo.png", url: "https://github.com/linuxserver/docker-filezilla" },
    { name: "Firefox", img: "firefox-logo.png", url: "https://github.com/linuxserver/docker-firefox" },
    { name: "Flycast", img: "flycast-logo.png", url: "https://github.com/linuxserver/docker-flycast" },
    { name: "Freecad", img: "freecad-logo.png", url: "https://github.com/linuxserver/docker-freecad" },
    { name: "Gimp", img: "gimp-logo.png", url: "https://github.com/linuxserver/docker-gimp" },
    { name: "Github Desktop", img: "github-desktop-icon.png", url: "https://github.com/linuxserver/docker-github-desktop" },
    { name: "Gitqlient", img: "gitqlient-icon.png", url: "https://github.com/linuxserver/docker-gitqlient" },
    { name: "Gzdoom", img: "gzdoom-logo.png", url: "https://github.com/linuxserver/docker-gzdoom" },
    { name: "Handbrake", img: "handbrake-logo.png", url: "https://github.com/linuxserver/docker-handbrake" },
    { name: "Inkscape", img: "inkscape-logo.png", url: "https://github.com/linuxserver/docker-inkscape" },
    { name: "Intellij Idea", img: "intellij-idea-logo.png", url: "https://github.com/linuxserver/docker-intellij-idea" },
    { name: "Joplin", img: "joplin-logo.png", url: "https://github.com/linuxserver/docker-joplin" },
    { name: "Kali Linux", img: "kali-logo.png", url: "https://github.com/linuxserver/docker-kali-linux" },
    { name: "Kdenlive", img: "kdenlive-logo.png", url: "https://github.com/linuxserver/docker-kdenlive" },
    { name: "Keepassxc", img: "keepassxc-logo.png", url: "https://github.com/linuxserver/docker-keepassxc" },
    { name: "Kicad", img: "kicad-logo.png", url: "https://github.com/linuxserver/docker-kicad" },
    { name: "Krita", img: "krita-logo.png", url: "https://github.com/linuxserver/docker-krita" },
    { name: "Libreoffice", img: "libreoffice-logo.png", url: "https://github.com/linuxserver/docker-libreoffice" },
    { name: "Librewolf", img: "librewolf-logo.png", url: "https://github.com/linuxserver/docker-librewolf" },
    { name: "Lollypop", img: "lollypop-icon.png", url: "https://github.com/linuxserver/docker-lollypop" },
    { name: "Mame", img: "mame-logo.png", url: "https://github.com/linuxserver/docker-mame" },
    { name: "Mediaelch", img: "mediaelch-logo.png", url: "https://github.com/linuxserver/docker-mediaelch" },
    { name: "Melonds", img: "melonds-logo.png", url: "https://github.com/linuxserver/docker-melonds" },
    { name: "Modrinth", img: "modrinth-logo.png", url: "https://github.com/linuxserver/docker-modrinth" },
    { name: "Msedge", img: "edge-logo.png", url: "https://github.com/linuxserver/docker-msedge" },
    { name: "Mullvad Browser", img: "mullvad-browser-logo.png", url: "https://github.com/linuxserver/docker-mullvad-browser" },
    { name: "Mysql Workbench", img: "mysql-workbench-icon.png", url: "https://github.com/linuxserver/docker-mysql-workbench" },
    { name: "Obsidian", img: "obsidian-logo.png", url: "https://github.com/linuxserver/docker-obsidian" },
    { name: "Onlyoffice", img: "onlyoffice-logo.png", url: "https://github.com/linuxserver/docker-onlyoffice" },
    { name: "Opera", img: "opera-icon.png", url: "https://github.com/linuxserver/docker-opera" },
    { name: "Orcaslicer", img: "orcaslicer-logo.png", url: "https://github.com/linuxserver/docker-orcaslicer" },
    { name: "Pcsx2", img: "pcsx2-logo.png", url: "https://github.com/linuxserver/docker-pcsx2" },
    { name: "Pidgin", img: "pidgin-logo.png", url: "https://github.com/linuxserver/docker-pidgin" },
    { name: "Ppsspp", img: "ppsspp-logo.png", url: "https://github.com/linuxserver/docker-ppsspp" },
    { name: "Pycharm", img: "pycharm-logo.png", url: "https://github.com/linuxserver/docker-pycharm" },
    { name: "Qdirstat", img: "qdirstat-logo.png", url: "https://github.com/linuxserver/docker-qdirstat" },
    { name: "Rawtherapee", img: "rawtherapee-logo.png", url: "https://github.com/linuxserver/docker-rawtherapee" },
    { name: "Remmina", img: "remmina-icon.png", url: "https://github.com/linuxserver/docker-remmina" },
    { name: "Retroarch", img: "retroarch-logo.png", url: "https://github.com/linuxserver/docker-retroarch" },
    { name: "Rpcs3", img: "rpcs3-logo.png", url: "https://github.com/linuxserver/docker-rpcs3" },
    { name: "Rustdesk", img: "rustdesk-logo.png", url: "https://github.com/linuxserver/docker-rustdesk" },
    { name: "Shotcut", img: "shotcut-logo.png", url: "https://github.com/linuxserver/docker-shotcut" },
    { name: "Signal", img: "signal-logo.png", url: "https://github.com/linuxserver/docker-signal" },
    { name: "Spotube", img: "spotube-logo.png", url: "https://github.com/linuxserver/docker-spotube" },
    { name: "Sqlitebrowser", img: "sqlitebrowser.svg", url: "https://github.com/linuxserver/docker-sqlitebrowser" },
    { name: "Steam", img: "steam-logo.png", url: "https://github.com/linuxserver/docker-steam" },
    { name: "Telegram", img: "telegram-logo.png", url: "https://github.com/linuxserver/docker-telegram" },
    { name: "Thunderbird", img: "thunderbird-logo.png", url: "https://github.com/linuxserver/docker-thunderbird" },
    { name: "Ungoogled Chromium", img: "ungoogled-chromium-logo.png", url: "https://github.com/linuxserver/docker-ungoogled-chromium" },
    { name: "Vivaldi", img: "vivaldi-logo.png", url: "https://github.com/linuxserver/docker-vivaldi" },
    { name: "Vlc", img: "vlc-logo.png", url: "https://github.com/linuxserver/docker-vlc" },
    { name: "Vscodium", img: "vscodium-icon.png", url: "https://github.com/linuxserver/docker-vscodium" },
    { name: "Webcord", img: "webcord-icon.png", url: "https://github.com/linuxserver/docker-webcord" },
    { name: "Webtop", img: "webtop-logo.png", url: "https://github.com/linuxserver/docker-webtop" },
    { name: "Weixin", img: "weixin-logo.png", url: "https://github.com/linuxserver/docker-weixin" },
    { name: "Wireshark", img: "wireshark-icon.png", url: "https://github.com/linuxserver/docker-wireshark" },
    { name: "Wps Office", img: "wps-office-icon.png", url: "https://github.com/linuxserver/docker-wps-office" },
    { name: "Xemu", img: "xemu-logo.png", url: "https://github.com/linuxserver/docker-xemu" },
    { name: "Yaak", img: "yaak-logo.png", url: "https://github.com/linuxserver/docker-yaak" },
    { name: "Zen", img: "zen-logo.png", url: "https://github.com/linuxserver/docker-zen" },
    { name: "Zotero", img: "zotero-icon.png", url: "https://github.com/linuxserver/docker-zotero" }
];
